### ISSUE TITLE
Troubles with importSVG in chrome 55

### ISSUE THREAD

**Issue by kondolovskiy** [paperjs/paper.js#1222]
After update chrome to 55 version, I have troubles with importSVG method (TypeError: item.setRampPoint is not a function at offset (paper-full.js:13213))

**Comment by kondolovskiy** [comment]
All works fine after update to latest version.

**Comment by lehni** [comment]
@kondolovskiy That's interesting. But I guess we already fixed that bug in the newer version?

Could you tell me something about the use of paper.js in reddit-plugin-gold? Can I see this life in action somewhere? Very curious!

**Comment by lehni** [comment]
Could you provide some SVG data that caused the original issue? I am trying to understand what caused this.

**Comment by abhishiv** [comment]
@lehni the following file for example give me the same error.

I found this bug because it breaks papergrapher, at [vol-2.com/papergrapher/](https://vol-2.com/papergrapher/).

[character_in_cape.svg.zip](https://github.com/paperjs/paper.js/files/704843/character_in_cape.svg.zip)

**Comment by lehni** [comment]
Ok, it seems that in the new versions (where `rampPoint` is now called `offset`) we're avoiding this simply by checking if `item.setOffset` actually is available:

```js
        offset: function(item, value) {
            if (item.setOffset) {
                var percent = value.match(/(.*)%$/);
                item.setOffset(percent ? percent[1] / 100 : parseFloat(value));
            }
        },
```

You could port that back to v0.9.25:

```js
        offset: function(item, value) {
            if (item.setRampPoint) {
                var percent = value.match(/(.*)%$/);
                item.setRampPoint(percent ? percent[1] / 100 : parseFloat(value));
            }
        },
```
