### ISSUE TITLE
Can no longer augment module after updating to v0.12.4

### ISSUE THREAD

**Issue by jkovzels** [paperjs/paper.js#1767]
# Description/Steps to reproduce

Facing some design time issues with types.

After updating to v0.12.4 I'm getting 

`error TS2671: Cannot augment module 'paper' because it resolves to a non-module entity.`

in my `paper.d.ts` where I declare some of Nodejs specific functions e.g. `exportImage` and `exportFrames`. Those methods not defined in original paper.d.ts.

# Link to reproduction test-case

see `repro.ts` [here](https://github.com/jkovzels/paperjs-tsd-repro)

run `yarn add paper@0.12.4` and `yarn build` to get the error.

# Expected result

Module can we augmented

# Additional information

Likely was caused by #1713 
Related issue in Typescript repo: https://github.com/Microsoft/TypeScript/issues/7148

**Comment by sasensi** [comment]
Hi, thank you for your report and for investigation the issue.  
Indeed, you are right about the commit causing this issue.  
Unfortunately, it seems hard to find a solution that fit all use cases and I think that the actual declaration shape is closer to what is really exported from the library (a `PaperScope` instance) than what is was before.  
The drawback is that, as you pointed out, this does not allow module augmentation pattern.  
With the current definition, you can workaround your issue like this:
```typescript
import { WriteStream } from "fs";
import * as paper from 'paper';

// Extend View class.
declare class ViewExtended extends paper.View
{
    exportImage(path: string, callback: Function): WriteStream;
    exportFrames(options: any): void;
}

// Extend PaperScope class.
declare class PaperExtended extends paper.PaperScope
{
    // Replace view property type.
    view: ViewExtended
    // Replace View constructor type.
    View: typeof ViewExtended
}

// Create an extended PaperScope instance.
const paperExtended:PaperExtended = paper as PaperExtended;

// Use it in your code.
paperExtended.setup(new paperExtended.Size(20, 20));
paperExtended.view.exportImage("", () => {});

// This works for constructor too.
const viewExtended = new paperExtended.View();
viewExtended.exportImage("", () => {});
```

This is not perfect as it requires some knowledge about the base typescript definition but it should do the trick.

I think that the real issue behind this is that the library can take different form depending on which platform it is used (node or browser) and this seems hard to handle within a single typescript definition.  
It seems to me that your use case is marginal (node + typescript) and I don't know if/how we should cover it ?
